const actionType = {
  FETCH_SIMILAR_MOVIES: "SIMILAR_MOVIES/FETCH_SIMILAR_MOVIES",
  FETCH_SIMILAR_MOVIES_LOADING: "SIMILAR_MOVIES/FETCH_SIMILAR_MOVIES_LOADING",
  FETCH_SIMILAR_MOVIES_ERROR: "SIMILAR_MOVIES/FETCH_SIMILAR_MOVIES_ERROR",
};

export default actionType;
